---
- name: Hello World Playbook
  hosts: server
  gather_facts: no # 对于这个简单的 playbook，我们不需要收集 facts

  tasks:
    - name: Send a Ping, expect a Pong
      ansible.builtin.ping:
        # ping 模块没有额外的参数，它只是尝试连接并返回 "pong"
